// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNssABzeBfhdIkEBe-mRd6_bfgTS7UGi8',
    appId: '1:1019192960498:web:65f06bad04fffabbbcf76b',
    messagingSenderId: '1019192960498',
    projectId: 'purrclean-124',
    authDomain: 'purrclean-124.firebaseapp.com',
    storageBucket: 'purrclean-124.firebasestorage.app',
    measurementId: 'G-YZCB25GV98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxArFHDJGBScgt0hiGRq6Q4tF--dLSWM',
    appId: '1:1019192960498:android:22259b3fc892ea28bcf76b',
    messagingSenderId: '1019192960498',
    projectId: 'purrclean-124',
    storageBucket: 'purrclean-124.firebasestorage.app',
  );
}
